[*] Running ...
[*] Dataset loaded: /home/dokhanhnam1199/QD/problems/tsp_aco/dataset/train50_dataset.npy with 5 instances.
Traceback (most recent call last):
  File "/home/dokhanhnam1199/QD/problems/tsp_aco/eval.py", line 53, in <module>
    obj = solve(node_pos)
  File "/home/dokhanhnam1199/QD/problems/tsp_aco/eval.py", line 26, in solve
    heu = heuristics(dist_mat.copy()) + 1e-9
  File "/home/dokhanhnam1199/QD/problems/tsp_aco/gpt.py", line 20, in heuristics_v2
    unvisited.remove(current_node)
IndexError: index 40 is out of bounds for axis 0 with size 40
15
2
95.90827503317318
