[*] Running ...
[*] Dataset loaded: C:\Users\Nam\Documents\GitHub\HSEvo/problems/cvrp_aco\dataset/train50_dataset.npy with 10 instances.
Traceback (most recent call last):
  File "C:\Users\Nam\Documents\GitHub\HSEvo/problems/cvrp_aco/eval.py", line 60, in <module>
    obj = solve(node_pos, demand)
  File "C:\Users\Nam\Documents\GitHub\HSEvo/problems/cvrp_aco/eval.py", line 28, in solve
    heu = heuristics(dist_mat.copy(), node_pos.copy(), demand.copy(), CAPACITY) + 1e-9
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nam\Documents\GitHub\HSEvo\problems\cvrp_aco\gpt.py", line 131, in heuristics_v2
  File "C:\Users\Nam\Documents\GitHub\HSEvo\problems\cvrp_aco\gpt.py", line 58, in random_removal
    best_insertion_index = best_index_for_node
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: pop index out of range
