[*] Running ...
[*] Dataset loaded: C:\Users\Nam\Documents\GitHub\HSEvo/problems/tsp_aco\dataset\train50_dataset.npy with 5 instances.
C:\Users\Nam\Documents\GitHub\HSEvo\problems\tsp_aco\gpt.py:21: RuntimeWarning: invalid value encountered in multiply
[*] Instance 0: 6.131047583816008
[*] Instance 1: 5.7385971230115445
[*] Instance 2: 6.6817896841672
[*] Instance 3: 6.524943386116298
[*] Instance 4: 6.4834933221594815
[*] Average:
6.311974219854107
