[*] Running ...
[*] Dataset loaded: /home/dokhanhnam1199/QD/problems/tsp_aco/dataset/train50_dataset.npy with 5 instances.
Traceback (most recent call last):
  File "/home/dokhanhnam1199/QD/problems/tsp_aco/eval.py", line 53, in <module>
    obj = solve(node_pos)
  File "/home/dokhanhnam1199/QD/problems/tsp_aco/eval.py", line 26, in solve
    heu = heuristics(dist_mat.copy()) + 1e-9
  File "/home/dokhanhnam1199/QD/problems/tsp_aco/gpt.py", line 56, in heuristics_v2
    # Selection (tournament selection)
IndexError: list index out of range
57
7
387.61964492324813
