[*] Running ...
/home/dokhanhnam1199/QD/problems/bpp_online/gpt.py:28: RuntimeWarning: invalid value encountered in sqrt
